version: "3.9"

networks:
  design_network:
    name: design_network

volumes:
  pgadmin:
  postgres:
  django_media:
  django_static:

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - django_media:/media
      - django_static:/static 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - design_network

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - design_network

  pgadmin:
    image: dpage/pgadmin4:4.23
    env_file: .env
    ports:
      - 15432:15432
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - design_network

  nginx:
    image: nginx:latest
    ports:
      - "17343:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_media:/var/html
      - django_static:/var/html 
    depends_on:
      - project
    networks:
      - design_network

