# Generated by Django 5.0.6 on 2024-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
